### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by hotequil** [Eihen/material-palette#1]
I try to compile my application, and Angular CLI throw this:

`
An error occurred during the build:
Error: The target entry-point "@eihen/material-palette-generator" has missing dependencies: @ctrl/tinycolor
`

**Comment by Eihen** [comment]
What angular version are you using?

Looks like something changed in one of the latest angular versions and it is not finding one of the dependencies.
As a temporary solution you can install [@ctrl/tinycolor](https://www.npmjs.com/package/@ctrl/tinycolor) in your project, I made a quick test and it works.

But I'll look into it with more detail later today and get back to you again.

**Comment by hotequil** [comment]
My Angular version is 11.2.x.

Thank you!! I installed the @ctrl/tinycolor dependency and fix this.
